require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: true
Bundler/OrderedGems:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
