---
name: RuboCop

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rubocop:
    # Ruby static code analyzer and formatter
    # https://github.com/rubocop/rubocop

    name: RuboCop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
